[package]
name = "dingtalk"
version = "0.1.0"
authors = ["Hatter Jiang <jht5945@gmail.com>"]
edition = "2018"
description = "DingTalk Util"
readme = "README.md"
repository = "https://git.hatter.ink/hatter/dingtalk"
license = "MIT"

[dependencies]
base64 = "0.11.0"
rust-crypto = "0.2.36"
reqwest = "0.9.22"
urlencoding = "1.0.0"
json = "0.11.14"
